FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN mkdir -p .git && npm ci

FROM node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_OPENPANEL_CLIENT_ID
ARG NEXT_PUBLIC_OPENPANEL_API_URL
ARG NEXT_PUBLIC_TORRENT_PROXY
ARG NEXT_PUBLIC_VERCEL_ENV=production
ARG NEXT_PUBLIC_VERCEL_URL=watchnext.noisy-silence.duckdns.org
ARG NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL=watchnext.noisy-silence.duckdns.org
ARG NEXT_PUBLIC_TITLE=Movie Advisor
ENV NEXT_PUBLIC_OPENPANEL_CLIENT_ID=$NEXT_PUBLIC_OPENPANEL_CLIENT_ID \
    NEXT_PUBLIC_OPENPANEL_API_URL=$NEXT_PUBLIC_OPENPANEL_API_URL \
    NEXT_PUBLIC_TORRENT_PROXY=$NEXT_PUBLIC_TORRENT_PROXY \
    NEXT_PUBLIC_VERCEL_ENV=$NEXT_PUBLIC_VERCEL_ENV \
    NEXT_PUBLIC_VERCEL_URL=$NEXT_PUBLIC_VERCEL_URL \
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL=$NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL \
    NEXT_PUBLIC_TITLE=$NEXT_PUBLIC_TITLE
RUN npm run build

FROM node:22-alpine AS run
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 3000
CMD ["npx", "next", "start", "-H", "0.0.0.0", "-p", "3000"]
